version: "3.9"

services:
  graphql: 
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  client: 
    build:
        context: client
        dockerfile: Dockerfile
    depends_on:
      - graphql
    ports:
      - "3000:3000"
